### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Save Start Task
POST localhost:8080/api/start/save
Content-Type: application/json

{
  "name":  "Fabricio Leite",
  "carRegistration": "BC-98-JP",
  "circuit":  "2825H",
  "initialKm":  844163,
  "numObjects": 154
}