### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create User
POST localhost:8080/api/save-data
Content-Type: application/json

{
  "firstName":  "Fabrcio",
  "lastName": "Leite",
  "email":  "fa@gmail.com",
  "contactNumber": "935118690",
  "address":  "Praceta Andre Resende 4",
  "city": "Almada",
  "state":  "Setubal",
  "country": "2810V"
}